input("Olá")
input("Qual é o seu nome?")
input("Quantos anos você tem?")
input("Você é homem ou mulher?")
input("Você é casado ou solteiro?")
input("Você tem filhos?")
input("Você trabalha?")
input("Você estuda?")